name: Build and Compress Directories

on:
  push:
    branches:
      - main

jobs:
  build-and-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install Protobuf
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Build Protobuf for Go
        run: |
          cd idl && protoc *.proto --go_out=. --go-grpc_out=. && cd ..

      - name: Build Protobuf for TypeScript
        run: |
          cd www && npx protoc --ts_out ./lib/pb -I ../idl --proto_path ../idl/common.proto ../idl/common.proto ../idl/api*.proto && cd ..

      - name: Compress directories
        run: |
          tar -czf idl.tar.gz idl
          tar -czf www.tar.gz www

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: directories
          paths:
            - idl.tar.gz
            - www.tar.gz
